export enum OrderStatus {
  NEW = 'NEW',
  PENDING_DESIGNER_ASSIGNMENT = 'PENDING_DESIGNER_ASSIGNMENT',
  IN_DESIGN = 'IN_DESIGN',
  PENDING_MANAGER_REVIEW = 'PENDING_MANAGER_REVIEW',
  PENDING_CLIENT_APPROVAL = 'PENDING_CLIENT_APPROVAL',
  IN_EMBROIDERY = 'IN_EMBROIDERY',
  READY_FOR_WAREHOUSE = 'READY_FOR_WAREHOUSE',
  SHIPPED = 'SHIPPED',
}
